version: '3.8'

services:
  docling:
    build:
      context: .
      dockerfile: Dockerfile
    image: docling:latest
    container_name: docling-service
    restart: always
    ports:
      - "33033:8000"
    volumes:
      - ./output:/app/output
      - ./docker_images:/app/static/images
    environment:
      - DOCLING_OUTPUT_DIR=/app/output
      - DOCLING_TEMP_DIR=/app/temp
      - TZ=Asia/Taipei
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s 